name: sidebar_animation
description: A flutter project for sidebar animation and page links

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player:
  flick_video_player: ^0.1.1
  flutter_widgets: ^0.1.12
  flutter_secure_storage: ^3.3.1+1
  flutter_form_builder: 3.14.0-alpha.1
  json_annotation: 3.0.1
  get_it: ^5.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  floating_bottom_navigation_bar: ^1.3.0
  provider : ^4.3.1
#  json_annotation: ^1.0.0
  http: any
  flutter_cache_manager: ^1.4.1
  cached_network_image: ^2.2.0+1
  shimmer: ^1.1.1
  splashscreen:
  shared_preferences: ^0.5.8
  flutter_session: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:
#  json_serializable: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/lmlogo.png
    - assets/images/guru1.png
    - assets/images/guru2.png
    - assets/images/guru3.png
    - assets/images/menu_background.png
    - assets/images/course1.png
    - assets/images/course2.png
    - assets/images/course3.png
    - assets/images/post1.png
    - assets/images/post2.png
    - assets/images/post3.png
    - assets/videos/background.mp4
    - assets/fonts/druk_medium.otf
    - assets/images/adventure3.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages